# Generated by Django 4.2 on 2024-08-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_profile_image_profile_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=16, null=True, verbose_name='취미')),
            ],
            options={
                'verbose_name': '취미',
                'verbose_name_plural': '취미',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=16, null=True, verbose_name='키워드')),
            ],
            options={
                'verbose_name': '키워드',
                'verbose_name_plural': '키워드',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='키'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(blank=True, choices=[('a', '학생'), ('b', '직장인'), ('c', '프리랜서/창업'), ('d', '준비 중')], max_length=1, null=True, verbose_name='직업'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_detail',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='직장 명'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mbti',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='흡연 여부'),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(choices=[('noreligion', '무교'), ('christianity', '기독교'), ('buddism', '불교'), ('catholicism', '천주교'), ('other', '기타'), ('noshow', '밝히기 싫어')], default='other', max_length=32, verbose_name='종교'),
        ),
        migrations.AddField(
            model_name='profile',
            name='school_level',
            field=models.CharField(blank=True, choices=[('a', '학사'), ('d', '석사'), ('e', '기타')], max_length=1, null=True, verbose_name='학력'),
        ),
        migrations.AddField(
            model_name='profile',
            name='school_major',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='학교 전공'),
        ),
        migrations.AddField(
            model_name='profile',
            name='school_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='학교 이름'),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoke',
            field=models.CharField(choices=[('no', '비흡연자'), ('yes', '흡연자'), ('electronic', '전자담배')], default='no', max_length=32, verbose_name='흡연 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.TextField(blank=True, max_length=15, null=True, verbose_name='도시'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='포인트'),
        ),
        migrations.AddField(
            model_name='profile',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='user.keyword', verbose_name='키워드'),
        ),
    ]
