# Generated by Django 4.2 on 2024-08-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_hobby_keyword_remove_profile_nickname_profile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='user.keyword', verbose_name='키워드'),
        ),
    ]
