# Generated by Django 4.2 on 2024-08-26 01:18

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=api.utils.FilenameChanger('profile'), verbose_name='아바타'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.utils.FilenameChanger('profile'), verbose_name='프로필 이미지'),
        ),
    ]
