# Generated by Django 4.2 on 2025-06-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_nickname_profile_avatar_profile_nickname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='MBTI'),
        ),
    ]
