# Generated by Django 4.2 on 2025-06-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_profile_likes_alter_profile_mbti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
