# Generated by Django 4.2 on 2025-06-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_delete_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nationality',
        ),
    ]
