# Generated by Django 4.2 on 2025-06-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_profile_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hobby',
            field=models.TextField(blank=True, null=True, verbose_name='취미'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='keywords',
        ),
        migrations.AddField(
            model_name='profile',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='키워드'),
        ),
    ]
