# Generated by Django 4.2 on 2025-06-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_profile_hobby_remove_profile_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blocked_profiles',
        ),
    ]
