# Generated by Django 4.2 on 2025-08-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_profileimage_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='is_avatar',
            field=models.BooleanField(default=False, verbose_name='대표 이미지'),
        ),
    ]
