# Generated by Django 4.2 on 2025-10-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_profileimage_is_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('MTF', '트랜스여성(MTF)'), ('CD', '크로스드레서')], default='M', max_length=5, verbose_name='성별'),
        ),
    ]
