version: "3.7"

services:
  app:
    build: .
    container_name: django
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/app
      - ./static:/static
    depends_on:
      - app

  redis:
    container_name: redis_service
    image: redis:latest
    ports:
      - "6379:6379"
