# Generated by Django 4.2 on 2025-06-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at'], 'verbose_name': '좋아요', 'verbose_name_plural': '좋아요'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_at'], 'verbose_name': '매칭', 'verbose_name_plural': '매칭'},
        ),
    ]
