# Generated by Django 4.2 on 2025-06-15 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(verbose_name='사용 금액')),
                ('description', models.CharField(max_length=200, verbose_name='사용 내역')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_usages', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '포인트 사용',
                'verbose_name_plural': '포인트 사용',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(verbose_name='충전 금액')),
                ('transaction_id', models.CharField(help_text='외부 결제 서비스 거래 ID', max_length=100, unique=True, verbose_name='거래 ID')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소')], default='pending', max_length=10, verbose_name='상태')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='결제 수단')),
                ('failure_reason', models.TextField(blank=True, null=True, verbose_name='실패 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '포인트 충전',
                'verbose_name_plural': '포인트 충전',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pointusage',
            index=models.Index(fields=['user', '-created_at'], name='payment_poi_user_id_bb83a3_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['user', '-created_at'], name='payment_poi_user_id_d841ff_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['transaction_id'], name='payment_poi_transac_494063_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['status'], name='payment_poi_status_e6cf71_idx'),
        ),
    ]
