# Generated by Django 4.2 on 2025-08-13 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('product_id', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('consumable', 'Consumable'), ('non_consumable', 'Non-consumable')], max_length=20)),
                ('environment', models.CharField(default='production', max_length=16)),
            ],
            options={
                'unique_together': {('store', 'product_id', 'environment')},
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('transaction_id', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('purchased', 'Purchased'), ('voided', 'Voided')], default='purchased', max_length=20)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('raw_summary', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('buy', 'Buy'), ('consume', 'Consume'), ('refund', 'Refund'), ('revoke', 'Revoke')], max_length=20)),
                ('source', models.CharField(choices=[('store_webhook', 'Store Webhook'), ('cron', 'Cron'), ('api', 'API')], max_length=20)),
                ('result', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payment.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=64)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('last_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['store', 'transaction_id'], name='payment_pur_store_4d0451_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entitlement',
            unique_together={('user', 'feature')},
        ),
    ]
