# Generated by Django 4.2 on 2025-10-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitlement',
            options={'verbose_name': '권한', 'verbose_name_plural': '권한'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '상품', 'verbose_name_plural': '상품'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': '구매', 'verbose_name_plural': '구매'},
        ),
        migrations.AlterModelOptions(
            name='purchaseevent',
            options={'verbose_name': '구매 내역', 'verbose_name_plural': '구매 내역'},
        ),
    ]
