# Generated by Django 4.2 on 2024-09-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('art_name', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='photos/')),
                ('image2', models.ImageField(upload_to='photos/')),
                ('image3', models.ImageField(upload_to='photos/')),
                ('image4', models.ImageField(upload_to='photos/')),
                ('image5', models.ImageField(upload_to='photos/')),
                ('when', models.DateField()),
                ('where', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('fixed', models.BooleanField(default=False)),
            ],
        ),
    ]
