# Generated by Django 4.2 on 2024-09-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_application_art_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '지원 가능 여부',
                'verbose_name_plural': '지원 가능 여부',
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': '공모전 지원 내역', 'verbose_name_plural': '공모전 지원 내역'},
        ),
        migrations.AddField(
            model_name='application',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='제출 일시'),
        ),
    ]
