# Generated by Django 4.2 on 2024-09-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_rename_art_name_application_art_name1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='참가 신청서'),
        ),
    ]
