# Generated by Django 4.2 on 2024-09-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_board_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='writer',
            field=models.CharField(max_length=255, verbose_name='작성자'),
        ),
    ]
