# Generated by Django 4.2 on 2024-09-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_alter_application_art_name1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='writer',
            field=models.CharField(default='운영사무국', max_length=255, verbose_name='작성자'),
        ),
    ]
